<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ec.edu.espe</groupId>
    <artifactId>arquitectura-23441</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>arquitectura-23441</name>

    <modules>
        <module>api-publicaciones</module>
        <module>ms-eureka-server</module>
        <module>ms-api-gateway</module>
        <module>ms-notificaciones</module>
        <module>ms-auth</module>
        <module>ms-catalogo</module>
    </modules>

</project>